Repository Himanshuu-Gupta/Simplii, pull requests merged in 2021-11, with the labels that each got.

#14 Add unit test samples
  UnitTests/config.json
  UnitTests/login_page_test.py
  UnitTests/sample_test.py
Labels: testing

#20 Phase-1 Documentation
  UnitTests/db_test.py
  docs/Phase1/Component Description.pdf
  docs/Phase1/Footer Screenshot.PNG
  docs/Phase1/Screenshot_Header.PNG
  docs/Phase1/Task list Screenshot.PNG
  docs/Phase1/VideoPresentation.mp4
  docs/Phase1/architectureImages/SE_ERDiagram.png
  docs/Phase1/architectureImages/webappFlowchart.png
  docs/Phase1/lintingEvidence/app.pyLinting.png
  docs/Phase1/proj1rubric.md
  docs/Phase1/proj1rubricComments
Labels: documentation

#24 Db schema documentation
  docs/Phase 2/DB_Schema.jpeg
Labels: documentation

#27 Update and Delete tasks
  src/controller/task_controller.py
  src/models/sql_helper.py
  src/models/task_model.py
Labels: enhancement

#30 SQL helper module
  src/models/sql_helper.py
Labels: enhancement

#32 Category Controller and Model
  src/controller/category_controller.py
  src/models/category_model.py
Labels: enhancement

#33 Adding database unit testing file
  UnitTests/database_tables_test.py
  UnitTests/db_test.py
  UnitTests/sql_helper.py
Labels: enhancement

#34 Database connection test
  UnitTests/database_connection_test.py
  UnitTests/database_crud_test.py
Labels: enhancement

#39 Fixes #38: Fixed backlog query issue
  src/models/task_model.py
Labels: bug

#55 Error handling
  app.py
  src/controller/home_controller.py
  src/error_handler/error.py
Labels: enhancement
